pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Assuming you're using Git
                git 'https://github.com/RicardoMPires/DevOps-23-24--PSM-1231857-.git'
            }
        }

        stage('Assemble') {
            steps {
                // This will run the 'assemble' task of Gradle
                sh './gradlew assemble'
            }
        }

        stage('Test') {
            steps {
                // This will run the 'test' task of Gradle
                sh './gradlew test'
            }
            post {
                always {
                    // This will archive the test results in Jenkins
                    junit '**/build/test-results/**/*.xml'
                }
            }
        }

        stage('Archive') {
            steps {
                // This will archive the JAR file in Jenkins
                archiveArtifacts artifacts: '**/build/libs/*.jar', fingerprint: true
            }
        }
    }
}