pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/RicardoMPires/DevOps-23-24--PSM-1231857-.git'
            }
        }

        stage('Setup Gradle Wrapper') {
            steps {
                script {
                    if (!fileExists('./CA2/Part1/gradle_basic_demo/gradle/wrapper/gradle-wrapper.jar')) {
                        sh './CA2/Part1/gradle_basic_demo/gradlew wrapper'
                    }
                }
            }
        }

        stage('Assemble') {
            steps {
                sh './CA2/Part1/gradle_basic_demo/gradlew assemble'
            }
        }

        stage('Test') {
            steps {
                sh './gradlew test'
            }
            post {
                always {
                    junit '**/build/test-results/**/*.xml'
                }
            }
        }

        stage('Archive') {
            steps {
                // This will archive the JAR file in Jenkins
                archiveArtifacts artifacts: '**/build/libs/*.jar', fingerprint: true
            }
        }
    }
}