pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/RicardoMPires/DevOps-23-24--PSM-1231857-.git'
            }
        }

        stage('Assemble') {
            steps {
            dir ('CA2/Part1/gradle_basic_demo'){
                sh './gradlew assemble'
            }
        }
        }

        stage('Test') {
            steps {
            dir ('CA2/Part1/gradle_basic_demo'){
                sh './gradlew test'
            }
            }
            post {
                always {
                    junit '**/build/test-results/**/*.xml'
                }
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: '**/build/libs/*.jar', fingerprint: true
            }
        }
    }
}